AllCops:
  Exclude:
    - 'bin/**/*'
    - '**/Rakefile'
    - 'Gemfile.lock'
    - 'db/schema.rb'
    - !ruby/regexp /node_modules/
    - "**/db/schema.rb"
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

#require: rubocop-rspec
