# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f2f65ca7d5e61667f9ce56a7bf1d13d96dcacda9dea04cf64f66c184f27e44b21f3436d61fbeb0f8c9b542d9d84d3160ef81c5d87ad3f308e94a389a6710d03

test:
  secret_key_base: 3871dd219d3d6c93baf1fd8490ba3aa1fe1e538c8fd666c13c462a8667f5ad69ff8fb7cfe281a54a7213ee14a13ae4a2f777c453229519316c18c876e522ec35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
